// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwi8JRoNZlm11-XGgQ3DpnIqD_JW4AjeU',
    appId: '1:878124695225:web:a649759776852e362c6568',
    messagingSenderId: '878124695225',
    projectId: 'camasirhane-fcde0',
    authDomain: 'camasirhane-fcde0.firebaseapp.com',
    databaseURL: 'https://camasirhane-fcde0-default-rtdb.firebaseio.com',
    storageBucket: 'camasirhane-fcde0.firebasestorage.app',
    measurementId: 'G-BKG6MGGFTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSYrEyNDLXz6UdaU6i5SQavyocATzhlok',
    appId: '1:878124695225:android:65e8c798c10b28832c6568',
    messagingSenderId: '878124695225',
    projectId: 'camasirhane-fcde0',
    databaseURL: 'https://camasirhane-fcde0-default-rtdb.firebaseio.com',
    storageBucket: 'camasirhane-fcde0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFNpG_VC6umcc4f2VMVE5In3hlvFxudgA',
    appId: '1:878124695225:ios:b512b9b2bdbe10ca2c6568',
    messagingSenderId: '878124695225',
    projectId: 'camasirhane-fcde0',
    databaseURL: 'https://camasirhane-fcde0-default-rtdb.firebaseio.com',
    storageBucket: 'camasirhane-fcde0.firebasestorage.app',
    iosBundleId: 'com.example.camasirhaneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFNpG_VC6umcc4f2VMVE5In3hlvFxudgA',
    appId: '1:878124695225:ios:b512b9b2bdbe10ca2c6568',
    messagingSenderId: '878124695225',
    projectId: 'camasirhane-fcde0',
    databaseURL: 'https://camasirhane-fcde0-default-rtdb.firebaseio.com',
    storageBucket: 'camasirhane-fcde0.firebasestorage.app',
    iosBundleId: 'com.example.camasirhaneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwi8JRoNZlm11-XGgQ3DpnIqD_JW4AjeU',
    appId: '1:878124695225:web:a4d90ebbef8e9b202c6568',
    messagingSenderId: '878124695225',
    projectId: 'camasirhane-fcde0',
    authDomain: 'camasirhane-fcde0.firebaseapp.com',
    databaseURL: 'https://camasirhane-fcde0-default-rtdb.firebaseio.com',
    storageBucket: 'camasirhane-fcde0.firebasestorage.app',
    measurementId: 'G-LZSC4V9F0Q',
  );
}
